"""empty message

Revision ID: 02ed1140e14a
Revises: 
Create Date: 2022-02-27 10:07:20.152320

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02ed1140e14a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("doors", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cars")
    # ### end Alembic commands ###
