"""empty message

Revision ID: 49517beae913
Revises: 02ed1140e14a
Create Date: 2022-02-28 22:32:13.267967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49517beae913'
down_revision = '02ed1140e14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
