"""empty message

Revision ID: fc22354ac9bf
Revises: 49517beae913
Create Date: 2022-02-28 22:32:57.769156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc22354ac9bf'
down_revision = '49517beae913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
